= Concurrent

== Project `Producer-Consumer`

=== Specification of task 1

Создать класс `Store` представляющий собой хранилище целых чисел. Для этого использовать структуру данных `LinkedList`

=== Specification of task 2

Создать метод `produce()`, который бесконечно добавляет в этот список случайные числа, однако максимальное количество, которое он может добавить равно 10.

=== Specification of task 3

Создать метод `consume()`, который бесконечно считывает числа с какой-то случайной задержкой (от 0 до 10 мс). При этом метод должны корректно работать в многопоточной среде.

=== Specification of task 4

Обновить метод `produce()`, что бы он добавлял числа только тогда, когда не превышен лимит. При этом метод должен корректно работать в многопоточной среде.

=== Specification of task 5

Обновить метод `consume()` что бы он забирал числа только тогда, когда в списке что-нибудь есть (использовать метод `removeFirst()` у `LinkedList` для получения элемента). При этом метод должен корректно работать в многопоточной среде.

=== Specification of task 6

Создать и запустить поток `ProducerThread`, который производит числа в `Store`.

=== Specification of task 7

Создать и запустить поток `ConsumerThread`, который потребляет числа из `Store`.

=== Specification of task 8

Продемонстрировать корректность работы хранилища в классе `NumberStoreDemo` с помощью вывода сообщений в консоль:

* добавлении
* получении
* текущем размере хранилища на этапах добавления и получения

== Project `SkyNet`

=== Specification of task 1

Написать эмуляцию игры. После восстания *SkyNet* мир роботов поделился на две фракции: *World* and *Wednesday*.

* Каждая из франций пытается создать армию роботов, но для этого им нужны детали для роботов.
* Детали для роботов делятся на:
** _head_
** _torso_
** _hand_
** _feet_
* Они производятся нейтральной *Factory*, которая каждый день, производит не более 10 деталей.
* Тип деталей выбирается случайным образом.
* Ночью фракции отправляются на фабрику, для того чтобы раздобыть детали для роботов (каждая может унести не более 5 деталей).
* Фракции и фабрика работают каждая в своем потоке.
* Определить у кого будет сильнее армия спустя 100 дней.

=== Specification of task 2*

Фракции не ограничены в количестве деталей

=== Specification of task 3**

Фракции стараются добыть детали которых у них не хватает

== Project `Store`

Напишите программу, моделирующую работу касс с покупателями в магазине:

* Существует несколько касс, работающих одновременно.
* Общее количество покупателей может быть больше, чем количество касс.
* Одновременно не может обрабатываться больше покупателей, чем имеется рабочих касс.
* У каждого покупателя есть набор товаров, которые должны быть выведены в процессе обслуживания.
