= Concurrency: utilities

NOTE: При выполнении заданий использовать не нативные инструменты Java, а инструменты из пакета `java.util.concurrent`

== Project 'Improved Parallel Calculator'

=== Specification of task 1

Реализовать метод:

* принимающий список массивов, состоящий из случайных целых чисел (от 1 до 300) случайной длины (до 1 млн элементов)
* возвращающий массивы и сумму элементов в них

=== Specification of task 2

Реализовать метод, аналогичный предыдущему, но принимающий количество потоков, в которых будет происходить выполнение.

=== Specification of task 3

Сравнить затраченное на выполнение время для списка массивов размерностью `10` для:

* метода работающего в 1 потоке
* метода работающего в 2 потоках
* метода работающего в 5 потоках
* метода работающего в 10 потоках

== Project 'Master-workers'

=== Specification of task 1

Написать программу, бесконечно считывающую целые числа, которые пользователь вводит в *Standard Input* .

=== Specification of task 2

При вводе `-1` программа завершает свою работу.

=== Specification of task 3

Когда пользователь вводит некоректные данные, то бросается собственный `UserInputException`.

=== Specification of task 4

Числа, вводимые пользователем, представляют собой количество секунд на которое должен заснуть _thread-worker_, который выводит в *File*: `${timestamp} - ${threadName} - I slept ${seconds} seconds`.

=== Specification of task 5

Все задачи, _thread-workers_ выполняет в том порядке, в котором они были введены пользователем.

=== Specification of task 6

Когда у _thread-worker_ нет текущих задач, то он выводит в *File*: `${timestamp} - ${threadName} - ...` и засыпает на 1 секунду.

== Project `Censor`*

* Пользователь с клавиатуры вводит путь к существующей директории и слово для поиска.
* После чего запускаются N потоков, которые для каждого файла в этой директории:
** проводят вырезание всех запрещенных слов (список этих слов нужно считать из файла с запрещенными словами).
* Для обработаных файлов выполняется слитие их содержимого в один файл.
* В методе main необходимо отобразить статистику выполненных операций.
