= Collection. Collections: List.

NOTE: Обязательным условием выполнения является тестирование классов.

== Project `Stack`

=== Specification of task 1

Реализуйте класс Stack` для работы с целыми значениями (стек целых). Стек должен иметь фиксированный размер.

=== Specification of task 2

Реализуйте набор операций для работы со стеком:

* помещение целого значения в стек
* выталкивание целого значения из стека
* подсчет количества целых в стеке
* проверку пустой ли стек
* проверку полный ли стек
* очистку стека
* получение значения без выталкивания верхнего целого в стеке

=== Specification of task 3

При старте приложения нужно отобразить меню с помощью, которого пользователь может выбрать необходимую операцию.

=== Specification of task 4

Измените стек таким образом, чтобы его размер был нефиксированным.

=== Specification of task 5

Сделать класс стека шаблонным.

== Project `Queue`

=== Specification of task 1

Создайте класс очереди для работы с символьными значениями. Требуется создать реализации для операций над элементами:

- `isEmpty()` — проверка очереди на пустоту
- `isFull()` — проверка очереди на заполнение
- `enqueue()` — добавление элемента в очередь
- `dequeue()` — удаление элемента из очереди
- `show()` — отображение всех элементов очереди на экран

При старте приложения нужно отобразить меню с помощью, которого пользователь может выбрать необходимую операцию.

=== Specification of task 2

Создайте класс очереди с приоритетами для работы с символьными значениями. Требуется создать реализации для операций над элементами очереди:

- `isEmpty()` — проверка очереди на пустоту
- `isFull()` — проверка очереди на заполнение
- `insertWithPriority()` — добавление элемента c приоритетом в очередь
- `pullHighestPriorityElement()` — удаление элемента с самым высоким приоритетом из очереди
- `peek()` — возврат самого большого по приоритету элемента. Обращаем ваше внимание, что элемент не удаляется из очереди
- `show()` — отображение всех элементов очереди на экран

При показе элемента также необходимо отображать приоритет.

=== Specification of task 3

При старте приложения нужно отобразить меню с помощью, которого пользователь может выбрать необходимую операцию.

=== Specification of task 4

Измените класс очереди из задания 1 сделав его шаблонным.

=== Specification of task 5

Измените класс очереди с приоритетами из задания 2 сделав его шаблонным.

== Project `Web Service`

=== Specification of task 1

Необходимо разработать приложение, которое позволит сохранять информацию о логинах пользователей и их паролях. Каждому пользователю соответствует пара логин — пароль. При старте приложение отображается меню:

* Добавить нового пользователя.
* Удалить существующего пользователя.
* Проверить существует ли пользователь.
* Изменить логин существующего пользователя.
* Изменить пароль существующего пользователя.

В зависимости от выбора пользователя выполняется действие, после чего меню отображается снова. Для решения задачи используйте подходящий класс из Java Collections Framework.

=== Specification of task 3

Разработать приложение, имитирующее очередь запросов к серверу.

* Должны быть клиенты, посылающие запросы на сервер, у каждого из которых есть свой приоритет.
* Каждый новый клиент попадает в очередь в зависимости от своего приоритета.
* Необходимо сохранять статистику запросов (пользователь, время) в отдельной очереди.
* Предусмотреть вывод статистики на экран.
