= JCF: Collection.

NOTE: Обязательным условием выполнения является тестирование классов.

== Project `StringCollectionUtil`

=== Specification of task 1

Создать класс:

* `StringCollectionUtil`

=== Specification of task 2

* В `StringCollectionUtil` добавить метод `resetWordsByLength()`, принимающий в качестве параметра коллекцию строк и размер слова.
* Метод замещает оригинальную строку, длина которой равна размеру слова, на "*".

Например:

Длина слова 4 символа. Первоначальная коллекция:

[source,json]
----
["this", "is", "lots", "of", "fun", "for", "every", "Java", "programmer"]
----

Коллекция после обработки методом:

[source,json]
----
["*", "is", "*", "of", "fun", "for", "every", "*", "programmer"]
----

=== Specification of task 3

* В `StringCollectionUtil` добавить метод `removeWordsByLength()`, который принимает коллекцию строк и размер слова.
* Метод удаляет из списка строк все строки длиной равной размерности слова.

== Other

NOTE: При реализации каждого из заданий нужно обязательно выбрать класс из Java Collections Framework, который подходит для решения задачи.

== Project `Pier`*

Создать имитационную модель «причал морских катеров». Необходимо вводить следующую информацию:

* Среднее время между появлениями пассажиров на причале в разное время суток.
* Среднее время между появлениями катеров на причале в разное время суток.
* Тип остановки катер (конечная или нет).

Необходимо определить:

* Среднее время пребывание человека на остановке.
* Достаточный интервал времени между приходами катеров, чтобы на остановке находилось не более N людей одновременно.
* Количество свободных мест в катере является случайной величиной.

== Project `Dictionary`*

Создать программу по работе со словарем. Например, англо-испанский или французско-немецкий, или любое другое направление.

Программа должна:

* обеспечивать начальный ввод данных для словаря
* позволять отобразить слово и его переводы
* позволять добавить, заменить, удалить переводы слова
* позволять добавить, заменить, удалить слово
* отображать топ-10 самых популярных слов (определяем популярность на основании счетчика обращений)
* отображать топ-10 самых непопулярных слов (определяем непопулярность на основании счетчика обращений)

