= JCF: List.

NOTE: Обязательным условием выполнения является тестирование классов.

== Project `Studio`

=== Specification of task 1

Создать класс `Actor`.

Поля:

* `firstName`
* `lastName`
* `fee`
* `age`

=== Specification of task 2

Создать класс `Studio`.

Поля:

* `actors` - список актеров, которые работают в студии.

Методы:

* `fire()` - принимает список актеров и удаляющий из него актера с наибольшим гонораром.

=== Specification of task 3

Написать компараторы, которые позволят отсортировать список актёров по:

* фамилии
* возрасту
* гонорару
* фамилии и возрасту
* гонорару и фамилии

== Project `Class`

=== Specification of task 1

Создать класс `Student`, представляющий собой ученика.

Поля:

* `name`
* `surname`
* `age`
* `averageAnnualMark`


=== Specification of task 2

Создать класс `SchoolClass`.

Поля:

* `students` - список учеников, которые учатся в `SchoolClass`

Методы:

* `getBestStudent()` - принимает список учеников и возвращает ученика с самым высоким средним баллом.

=== Specification of task 3

Написать компараторы, которые позволят отсортировать список учеников по:

* полному имени (имя + фамилия)
* возрасту
* среднему баллу
