= Lambda Expressions (JSR 335)

== Specification Task 1

Дан массив аргументов и значений для них, в следующем виде:

[source, text]
----
"-i", "in.txt", "--limit", "40", "-d", "1", "-o", "out.txt"
----

* реализовать метод возвращающий `Map`, где `key` - название аргумента, `value` - значение аргумента
* реализовать метод конвертирующий `Map` с аргументами и их значениями в массив строк

== Specification Task 2

Вывести таблицу умножения от 1 до 10.

* в 1 столбец
* в 5 столбцов


== Project `Math's statistics`

Написать utility class, который реализует следующие методы:

* генерация набора случайных целых чисел
* подсчет количества:
** четных
** нечетных
** равных 0
** равных некоторому значению

== Project `City Helper`

Дан список городов (города могут повторяться).

Написать utility class, который реализует следующие методы:

* получение всех городов:
** уникальных
** с названием, которое длиннее шесть символов
** начинающихся на заданную букву
* колучение количества употребления конкретного города в списке

== Project `TV`

Дан список телевизоров. Каждый телевизор имеет:

* производителя
* названии модели
* год выпуска
* диагональ
* цену

Написать utility class, который реализует следующие методы:

* получение телевизоров:
** с заданной диагональю
** какого-то производителя
** не старше какого-то года
** с ценой в каком-то диапазоне
** отсортированные по цене (по возрастанию)
** отсортированные по цене (по убыванию)
** отсортированные по диагонали (по возрастанию)
** отсортированные по диагонали (по убыванию)

== Project 'University'*

Дан список студентов. Каждый студент имеет:

* имя
* фамилию
* специальность
* курс

Написать utility class, который реализует следующие методы:

* групировка студентов по курсу
* получение списка специальностей (в алфавитном порядке), на которых учатся студенты
* получение количество учащихся на каждой из специальностей
* групировка студентов по специальностям (сохраняя алфавитный порядок специальности), а затем группировки по курсу
* проверка, есть ли среди учащихся кокретного курса, за исключение списка каких-то специальностей
