= Concurrency. Thread synchronization.

TIP: Когда нескольким потокам необходимо работать с одними и теми же данными, то создается _общий ресурс_, доступ к которому имеют все эти потоки.

TIP: Не использовать поток `main`, как поток, который выполняет какую-то задачу/работу. Чаще всего поток `main` является _координирующим_ потоком, т.е. потоком где создаются другие потоки, общие ресурсы для этих потоков и т.д.

TIP: Необходимо корректно выделить задачу/работу, которую можно выполнить в отдельном потоке.

== Project `Producer-Consumer`

WARNING: Обязательное требование: корректная работа в многопоточной среде.


=== Specification of task 1

Создать класс `Store` представляющий собой хранилище целых чисел.

=== Specification of task 2

Добавить в класс `Store` метод `produce()`, который принимает и добавляет в хранилище простое число. Максимальное количество чисел, которое может содержать в `Store` равно `10`.

=== Specification of task 3

Добавить в класс `Store` метод `consume()`, который забирает из `Store` (т.е. число удаляется из него).

=== Specification of task 4

Создать и запустить несколько потоков `ProducerThread`, которые производят числа для `Store`.

=== Specification of task 5

Создать и запустить несколько потоков `ConsumerThread`, которые потребляют числа из `Store`.

=== Specification of task 6

Добавить логирование (в виде вывода в *Standard Output* или файл) всех ключевых этапов работы потоков.

== Project `SkyNet`

=== Specification of task 1

Написать эмуляцию игры. После восстания *SkyNet* мир роботов поделился на две фракции: *World* and *Wednesday*.

* Каждая из фракций пытается создать армию роботов, но для этого им нужны детали для роботов.
* Детали для роботов делятся на:
** _head_
** _torso_
** _hand_
** _feet_
* Детали производятся нейтральной *Factory*.
** Каждый день, в светлое время суток, *Factory* производит не более 10 деталей.
** Тип деталей случайный.
* Ночью фракции отправляются на фабрику, для того, чтобы раздобыть детали для роботов.
** Каждая фракция может унести не более 5 деталей.
* Фракции и фабрика работают каждая в своем потоке.
* Определить у кого будет сильнее армия спустя N дней.

=== * Specification of task 2

Фракции стараются добыть детали которых у них не хватает.

=== * Specification of task 3

Фракции не ограничены в количестве деталей.

== * Project `Store`

Напишите программу, моделирующую работу касс с покупателями в магазине:

* Существует несколько касс, работающих одновременно.
* Общее количество покупателей может быть больше, чем количество касс.
* Одновременно не может обрабатываться больше покупателей, чем имеется рабочих касс.
* У каждого покупателя есть набор товаров, которые должны быть выведены в процессе обслуживания.
