= Concurrent utilities

NOTE: При выполнении заданий использовать не нативные инструменты Java, а инструменты из пакета `java.util.concurrent`

== Project 'Improved Parallel Calculator'

TIP: Если есть некоторое количество однотипных задач, то их следует выполнять параллельно. При этом возникает необходимость управления параллельным выполнением этих задач и сохранения их результата.

=== Specification of task 1

Реализовать метод:

* принимающий список массивов, состоящий из случайных целых чисел (от 1 до 300) случайной длины (до 1 млн элементов)
* возвращающий массивы и сумму элементов в них

=== Specification of task 2

Реализовать метод, аналогичный предыдущему, но принимающий количество потоков, в которых будет происходить выполнение.

=== Specification of task 3

Сравнить затраченное на выполнение время для списка массивов размерностью `10` для:

* метода работающего в 1 потоке
* метода работающего в 2 потоках
* метода работающего в 5 потоках
* метода работающего в 10 потоках

== Project 'Improved Producer-Queue-Consumer'

=== Specification of task 1

Реализовать поток *Producer* бесконечно считывающий целые числа, которые пользователь вводит в *Standard Input*.

=== Specification of task 2

Поток *Producer* сохраняет целые числа в *Queue*.

=== Specification of task 3

При вводе `-1` поток *Producer* завершает свою работу.

=== Specification of task 4

Когда пользователь вводит некорректные данные, то поток *Producer* бросает исключение `UserInputException`, но при этом продолжает работать.

=== Specification of task 5

Реализовать поток *Consumer*, который забирает числа из *Queue* и засыпает на количество секунд равное этому числу. При этом засыпание потока *Consumer* происходит в том порядке, в котором значения целых чисел были введены пользователем.

=== Specification of task 6

После того как поток *Consumer* проснется, он выводит в *File*: `${timestamp} - ${thread-name} - I slept ${seconds} seconds`.

=== Specification of task 7

Когда у потока *Consumer* нет текущих задач, то он выводит в *File*: `${timestamp} - ${thread-name} - ...` и засыпает на 1 секунду.

=== Specification of task 8

Добавить несколько потоков *Consumer*.

=== * Specification of task 9

Добавить возможность конфигурации количества *Consumer* потоков.
