= Custom Array List

== Конструкторы

* Принимает аргумент типа `int`, который задает начальную емкость массива (`capacity`), т. e. выделяет память под массив.
Начальный размер (`size = 0`)

* Без параметров (по умолчанию), который выделяет память под массив на 10 элементов (`capacity = 10`,
`size = 0`).
Данный конструктор использует конструктор с параметром, для уменьшения кода.

== Методы

* `getSize()` - метод возвращающий размер Custom Array List.

* `toString()` - @Override метод выводящий элементы Custom Array List.

* `pushBack()` - добавление элемента в конец Custom Array List.

* `popFront()` - удаление первого элемента из Custom Array List.

* `pushFront()` - добавление нового элемента в начало Custom Array List.

* `insert()` - вставка нового элемента в Custom Array List по указанному индексу.

* `removeAt()` - удаление одного элемента по указанному индексу.

* `remove()` - удаление одного элемента, значение которого совпадает со значением переданного параметра.

* `removeAll()` - удаление всех элементов, значения которых совпадает со значением переданного параметра.

* `popBack()` - удаление последнего элемента из Custom Array List.

* `clear()` - обнуление Custom Array List.

* `isEmpty()` - метод возвращает `true`, если `size = 0`, и `false` в обратном случае

* `trimToSize()` - метод подгоняет значение `capacity` под `size`

* `indexOf()` - линейный поиск слева направо первого вхождения в массив указанного значения.
В результате работы возвращается индекс найденного элемента, а если ничего не найдено, возвращается `-1`

* `lastIndexOf()` - линейный поиск справа налево вхождения в массив указанного значения.
В результате работы возвращается индекс найденного элемента, а если ничего не найдено, возвращается `-1`


* `reverse()` - изменение порядка следования элементов в массиве на противоположный

* `shuffle()` - случайное перемешивание элементов массива

* `equals()` - в качестве параметра передается ссылка на другой объект класса `CustomArrayList`.
Метод сравнивает массивы не только по количеству элементов, но и по их содержимому

* `getElementAt()` - возврат копии элемента массива по указанному индексу
