= Generics

== Project: 'Obscure'

Создать обобщенный класс `Obscure`.
Этот класс фактически является оберткой над объектом и помогает работать с `NullPointerException`.

=== Specification of task 1

Добавить *field*, которое хранит в себе объект обобщенного типа.

WARNING: Переменные любого объектного типа могут хранить в качестве значения и `null`.

=== Specification of task 2

Добавить конструктор, который принимает объект обобщенного типа.

=== Specification of task 3

Добавить метод `get()` (не путать с *getter* для *field*), который возвращает объект обобщенного типа.

=== Specification of task 4

Добавить метод `isPresent()`, который возвращает ответ типа `Boolean`, означающий существует ли объект обобщенного типа.

=== Specification of task 5

Добавить метод `isEmpty()`, который возвращает ответ типа `Boolean`, означающий пустой ли объект обобщенного типа.

=== Specification of task 6

Добавить метод `orElse()`, который принимает объект обобщенного типа (далее *default object*). Метод возвращает объект обобщенного типа, который хранится в `Obscure`. Если его не существует, метод возвращает *default object*.

=== Specification of task 7

Добавить метод `orElseThrow()`, который принимает исключение. Если объект обобщенного типа существует, то он возвращает.
Если объект обобщенного типа не существует, то он выбрасывает исключение, которое передано в метод.

=== Specification of task 8

Добавить статический метод `of()`, который возвращает объект `Obscure` обобщенного типа.
Этот метод принимает объект обобщенного типа.

=== Specification of task 9

Добавить статический метод `empty()`, который возвращает пустой объект `Obscure` обобщенного типа.

== Project: 'Pair'

=== Specification of task 1

Создать класс `Pair` (пара), обобщенный двумя параметрами типа `K` и `V`:

* имеет два поля типов `K` и `V`
* имеет конструктор, принимающий 2 параметра типов `K` и `V`
* имеет *getters* и *setters* для обоих полей

=== Specification of task 2

Добавить методы:

* обобщенный `getSwapped()`, который возвращает текущую `Pair`, где элементы пары поменяли местами
* статический обобщенный `swap()`, принимающий параметр `Pair` и возвращающий `Pair`, где значения в паре поменяли местами

== Project: 'Math'

Создать абстрактный класс `Math`, который представляет собой массив, позволяющий хранить объекты числового типа.

=== Specification of task 1

Реализуйте статический обобщенный метод, который возвращает максимум из трёх переданных параметров.

=== Specification of task 2

Реализуйте статический обобщенный метод, который возвращает минимум из пяти переданных параметров.

=== Specification of task 3

Реализуйте статический обобщенный метод для поиска среднеарифметического значения в массиве.

=== Specification of task 4

Реализуйте статический обобщенный метод для поиска максимума в массиве.

=== Specification of task 5

Реализуйте статический обобщенный метод для поиска минимума в массиве.

=== * Specification of task 6

Реализуйте обобщенный метод для сортировки массива.
Сортировку реализовать самостоятельно.

=== * Specification of task 7

Реализуйте статический обобщенный метод для двоичного поиска в массиве.
Двоичный поиск реализовать самостоятельно.

== * Project: 'Array'

Создайте обобщенный класс `Array`, который представляет собой массив, позволяющий хранить объекты числового типа.

=== Specification of task 1

Реализовать обобщенные методы:

* заполнение массива с клавиатуры
* заполнение массива случайными числами
* отображение массива
* поиск максимального значения
* поиск минимального значения
* подсчет среднеарифметического значения
* сортировка массива по возрастанию
* сортировка массива по убыванию
* поиск значения в массиве, используя бинарный поиск
* замена значения в массиве на новое значение

== ** Project: 'Custom Array List'

Написать обобщенный класс, реализующий логику работы одномерного безразмерного динамического массива.

* Имя класса `CustomArrayList`.
* Структура данных – массив.
* Типы хранимых данных – объекты любых классов.
* Все открытые методы должны содержать *javadoc*.
* Все открытые методы должны быть протестированы.

=== Specification of task 1

Создать в классе три поля:

* `data` - ссылка на инкапсулированный массив;
* `size` - текущее количество существующих элементов в массиве;
* `capacity` - текущая емкость массива (по умолчанию `10`).

=== Specification of task 2

Создать два конструктора:

* С параметром типа `int`, задающего начальную емкость массива.
Принимает один параметр (т.е. задает `capacity`), выделяет память под массив (`size = 0`).
* Без параметров (по умолчанию), который выделяет память под массив на 10 элементов, равных нулю (`capacity = 10`,
`size = 0`).
* Переиспользовать конструктор с параметрами для уменьшения кода.

=== Specification of task 3

Реализовать методы:

* `getSize()`.
** Сеттера для `size` не должно быть
* переопределить метод `toString()` и реализовать строковое представление элементов массива через пробел
* `ensureCapacity()` – закрытый метод, который проверяет, достаточно ли резерва памяти для хранения указанного в параметре количества элементов.
** Если значение параметра меньше текущего `capacity`, то ничего не происходит.
** Если значение параметра больше текущего `capacity`, то массив пересоздается, памяти выделяется в 1,5 раза + 1 элемент больше.
Существующие элементы не должны быть потеряны, они переносятся в новый массив.

=== Specification of task 4

Реализовать методы:

* `pushBack()` - добавление элемента в конец массива.
** Должна быть проверка, достаточно ли памяти
** Если памяти недостаточно увеличить емкость массива данных
* `popFront()` - удаление первого элемента из массива
* `pushFront()` - добавление нового элемента в начало массива
* `insert()` - вставка нового элемента в массив по указанному индексу, с проверкой на выход за пределы массива
* `removeAt()` - удаление одного элемента по указанному индексу.
** Должна быть проверка на допустимость индекса
* `remove()` - удаление одного элемента, значение которого совпадает со значением переданного параметра
* `removeAll()` - удаление всех элементов, значения которых совпадает со значением переданного параметра
* `popBack()` - удаление последнего элемента из массива
* `clear()` - обнуление массива – всем элементам массива по индексам от `0` до `size - 1` присвоить значение `null`, полю
`size` присвоить значение `0`

=== Specification of task 5

Реализовать методы:

* `isEmpty()` - метод возвращает `true`, если `size = 0`, и `false` в обратном случае
* `trimToSize()` - метод подгоняет значение `capacity` под `size`, естественно уменьшая размер используемой памяти
* `indexOf()` - линейный поиск слева направо первого вхождения в массив указанного значения.
В результате работы вернуть индекс найденного элемента, а если ничего не найдено, вернуть `-1`
* `lastIndexOf()` - линейный поиск справа налево вхождения в массив указанного значения.
В результате работы вернуть индекс найденного элемента, а если ничего не найдено, вернуть `-1`

=== Specification of task 6

Реализовать методы:

* `reverse()` - изменение порядка следования элементов в массиве на противоположный
* `shuffle()` - случайное перемешивание элементов массива

=== Specification of task 7

Реализовать методы:

* `equals()` - в качестве параметра передается ссылка на другой объект класса `CustomArrayList`.
Метод сравнивает массивы не только по количеству элементов, но и по их содержимому
* `getElementAt()` - возврат копии элемента массива по указанному индексу, с проверкой на выход за пределы массива

Переопределить методы:

* `clone()` - метод создает точную копию `CustomArrayList` и возвращает ссылку на эту копию

== ** Project: 'Matrix'

Создайте обобщенный класс `Matrix`, который представляет собой массив, позволяющий хранить объекты числового типа.

=== Specification of task 1

Необходимо реализовать:

* заполнение матрицы с клавиатуры
* заполнение случайными значениями
* отображение матрицы
* поиск максимального и минимального элемента
* подсчет среднеарифметического значения

=== ** Specification of task 2

Дополнительно реализовать:

* арифметические операции `+`, `-`, `*`, `/` по правилам работы с матрицами
