= Java IO

NOTE: Реализация методов не должна зависеть от OS.

== Project `File Util`

Создать класс утилиту `FileUtil`.

=== Specification of task 1

Реализовать метод, который принимает пути к двум файлам. Метод переписывает содержимое одного файла в другой файл, но только в ВЕРХНЕМ РЕГИСТРЕ.

=== Specification of task 2

Реализовать метод, который принимает путь к файлу. Метод возвращает список строк этого файла.

=== Specification of task 3

Реализовать метод, который принимает путь к файлу. Метод возвращает список слов начинающихся с гласной буквы.

=== Specification of task 4

Реализовать метод, который принимает путь к файлу. Метод возвращает список слов, для которых последняя буква совпадает с первой буквой следующего за ним слова.


=== Specification of task 5

Реализовать метод, который принимает путь к файлу. Метод возвращает список наибольшей комбинации цифр для каждой строки, которые идут в порядке возрастания.

Например:

Input:

----
1 2 1 2 3
67 68 69 23
----

Output:
----
"1 2 3", "67 68 69"
----

=== Specification of task 6

Реализовать метод, который принимает путь к файлу. Метод возвращает частоту повторяемости всех букв в тексте, игнорируя регистр.

=== Specification of task 7

Реализовать метод, который принимает путь к файлу. Метод возвращает частоту повторяемости всех слов в тексте в порядке возрастания частоты повторяемости.

=== Specification of task 8

Реализовать метод, который принимает путь к файлу с целыми числами и сортирующий содержимое файла по возрастанию и сохраняющий результат в файл `${origin_filepath}_`.

=== Specification of task 9

Реализовать метод, который принимает путь к файлу, где содержится фамилия студентов и их оценки (в качестве разделителя используется `,`) и возвращает успеваемость студентов.

=== Specification of task 10

Реализовать метод, который принимает путь к файлу с java кодом, и 2 модификатора доступа в виде строки и заменяет все модификаторы доступа `X` в объявлении атрибутов и методов класса на `Y` и сохраняющий результат в файл `${origin_filepath}_`.

== *Project `Computer repair workshop`

=== Specification of task 1

* Создать класс `Computer`.
* Добавить ему несколько полей, создать объект этого класса, сериализовать в файл.
* Десериализовать объект из того же файла, вывести значения полей в консоль.

=== Specification of task 2

* Создать класс `Notebook` - наследник `Computer`.
* В этом классе должно быть поле типа `Touchpad` - также созданного класса со своими полями.
* Добавить в класс `Notebook` `transient`-поле.
* Создать объект класса `Notebook`, сериализовать в файл.
* Десериализовать объект из файла, продемонстрировать, что `transient`-поля не сериализуются.
