= JCF: Collection.

WARNING: Без необходимости не стоит использовать более низкие уровни абстракции. Например: если задача решается с помощью API для `Collection`, то не стоит указывать для нее переменную типа `List`, тем более `ArrayList`.

== Project `StringCollectionUtil`

Разработать класс `StringCollectionUtil` для работы с коллекцией строк.

=== Specification of task 1

* В `StringCollectionUtil` добавить метод `resetWordsByLength()`, принимающий в качестве параметра список строк и размер слова.
* Метод заменяет оригинальную строку, длина которой равна размеру слова, на `*`.

Например:

Длина слова 4 символа. Первоначальная коллекция:

[source,json]
----
["this", "is", "lots", "of", "fun", "for", "every", "Java", "programmer"]
----

Коллекция после обработки методом:

[source,json]
----
["*", "is", "*", "of", "fun", "for", "every", "*", "programmer"]
----

=== Specification of task 2

* В `StringCollectionUtil` добавить метод `removeWordsByLength()`, который принимает коллекцию строк и размер слова.
* Метод удаляет из списка строк все строки длиной равной размерности слова.

== Other

NOTE: При реализации каждого из заданий нужно обязательно выбрать класс из Java Collections Framework, который подходит для решения задачи.

== ** Project `Pier`

Создать имитационную модель «причал морских катеров». Необходимо вводить следующую информацию:

* Среднее время между появлениями пассажиров на причале в разное время суток.
* Среднее время между появлениями катеров на причале в разное время суток.
* Тип остановки катер (конечная или нет).

Необходимо определить:

* Среднее время пребывание человека на остановке.
* Достаточный интервал времени между приходами катеров, чтобы на остановке находилось не более N людей одновременно.
* Количество свободных мест в катере является случайной величиной.

== ** Project `Web Service`

=== Specification of task 1

Необходимо разработать приложение, которое позволит сохранять информацию о логинах пользователей и их паролях. Каждому пользователю соответствует пара логин — пароль. При старте приложение отображается меню:

* Добавить нового пользователя.
* Удалить существующего пользователя.
* Проверить существует ли пользователь.
* Изменить логин существующего пользователя.
* Изменить пароль существующего пользователя.

В зависимости от выбора пользователя выполняется действие, после чего меню отображается снова. Для решения задачи используйте подходящий класс из Java Collections Framework.

=== Specification of task 3

Разработать приложение, имитирующее очередь запросов к серверу.

* Должны быть клиенты, посылающие запросы на сервер, у каждого из которых есть свой приоритет.
* Каждый новый клиент попадает в очередь в зависимости от своего приоритета.
* Необходимо сохранять статистику запросов (пользователь, время) в отдельной очереди.
* Предусмотреть вывод статистики на экран.
