= JCF: Queue.

==  Project `WrapperQueue`

Создайте класс-обертку очереди для работы с любыми объектами.

=== Specification of task 1

Требуется создать реализации для операций над элементами:

- `isEmpty()` — проверка очереди на пустоту
- `isFull()` — проверка очереди на заполнение
- `enqueue()` — добавление элемента в очередь
- `dequeue()` — удаление элемента из очереди
- `show()` — отображение всех элементов очереди на экран

При старте приложения нужно отобразить меню с помощью, которого пользователь может выбрать необходимую операцию.

=== Specification of task 2

Измените класс очереди сделав его параметризованным.

== * Project `Priority Queue`

Создайте класс-обертку очереди с приоритетом для работы с любыми объектами.

=== Specification of task 1

Требуется создать реализации для операций над элементами очереди:

- `isEmpty()` — проверка очереди на пустоту
- `isFull()` — проверка очереди на заполнение
- `insertWithPriority()` — добавление элемента c приоритетом в очередь
- `pullHighestPriorityElement()` — удаление элемента с самым высоким приоритетом из очереди
- `peek()` — возврат самого большого по приоритету элемента. Обращаем ваше внимание, что элемент не удаляется из очереди
- `show()` — отображение всех элементов очереди на экран

При показе элемента также необходимо отображать приоритет.

=== Specification of task 2

Измените класс очереди с приоритетами сделав его параметризованным.

== * Project `CustomStack`

Реализуйте класс `Stack` для работы с целыми числами. Стек должен иметь фиксированный размер.

=== Specification of task 1

Реализуйте набор операций для работы со стеком:

* помещение целого значения в стек
* выталкивание целого значения из стека
* подсчет количества целых в стеке
* проверку пустой ли стек
* проверку полный ли стек
* очистку стека
* получение значения без выталкивания верхнего целого в стеке

=== Specification of task 2

Измените стек таким образом, чтобы его размер был нефиксированным.

=== Specification of task 3

Сделать класс стека параметризованным.
