= JSF: Map

== Project `Words monitoring`

=== Specification of task 1

Создать класс:

* `TextMonitoring`

=== Specification of task 2

* Добавить метод `researchText()`, принимающий в качестве параметра текст.
* Метод выделяет все различные слова и высчитывает частоту, с которой они встречаются.
* Слова считаются различными даже если у них отличается регистром букв.

=== Specification of task 3

Добавить методы:

- `getCountUniqueWords()` возвращает количество уникальных слов в тексте
- `getUniqueWords()` возвращает коллекцию уникальных слов из текста
- `getFrequencyWord(word)` возвращае частоту употребления слова `word`
- `getFrequencyWords(boolean isAscendingFrequency)` возвращает все слова и частоту их употребления, `isAscendingFrequency` - если `true`, то по возрастанию, иначе по убыванию

== * Project `Garage`

=== Specification of task 1

Создать абстрактный класс представляющий автомобиль:

- `Car`

=== Specification of task 2

Добавить поля:

* `brand`
* `model`
* `color`
* `yearManufacture`
* `registrationNumber`

=== Specification of task 3

Создать 4 класса, являющихся наследниками `Car`.

=== Specification of task 4

Переопределить у класса `Car` методы:

* `equals()`
* `hashCode()`
* `toString()`

=== Specification of task 5

Создать класс `Garage`, который хранит `Map` c автомобилями, где ключом является производитель и модель автомобиля, значением - список автомобилей в гараже данного производителя и модели.

=== Specification of task 6

Добавить в класс `Garage`:

* `park(car)`
* `leave(car)`
* `getCount(brand, model)`
* `isExist(registrationNumber)`
* `isExist(brand, model, registrationNumber)`
* `getByRegistrationNumber(registrationNumber)`

== * Project `Dictionary`

Создать программу по работе со словарем. Например, англо-испанский или французско-немецкий, или любое другое направление.

Программа должна:

* обеспечивать начальный ввод данных для словаря
* позволять отобразить слово и его переводы
* позволять добавить, заменить, удалить переводы слова
* позволять добавить, заменить, удалить слово
* отображать топ-10 самых популярных слов (определяем популярность на основании счетчика обращений)
* отображать топ-10 самых непопулярных слов (определяем непопулярность на основании счетчика обращений)
