= Regular Expressions

== Specification of task 1

Написать программу:

* выполняющую поиск шестнадцатеричных чисел (записанных по правилам Java) в строке
* выводящую эти числа *Standard Output*.

== Specification of task 2

Написать программу:

* выполняющую поиск в строке всех тегов `<p>`, в т.ч. тех, у которых есть атрибуты, например `<p id ="first">`
* заменяющую их на простые теги абзацев `<p>`.

== Specification of task 3

Написать программу:

* выполняющую поиск в строке мобильных телефонных номеров в формате `+375XXYYYYYYY`
* заменяющую каждый номер телефона на тот же номер, но в формате `+375 (XX) YYY-YY-YY`

`X` - символы для кода оператора
`Y` - символы для номера телефона

== Specification of task 4

Написать валидатор, который проверяет является ли введённая строка адресом почтового ящика.

Требования:

* в названии почтового ящика можно использование только:
** буквы
** цифры
** нижние подчёркивания
* название почтового ящица должно начинаться с буквы
* возможные домены верхнего уровня:
** `by`
** `org`
** `com`

== Project 'Public Transport Timetable'**

Задан текстовый файл с описанием четырёхдневных курсов в следующем виде:

[source, text]
----
09:20 Введение
11:00 Упражнения
11:15 Перерыв
11:35 Скаляры
12:30 Обеденный перерыв
13:30 Упражнения
14:10 Решения
14:30 Перерыв
14:40 Массивы
15:40 Упражнения
17:00 Решения
17:30 Конец
 
09:30 Углубленное изучение массивов
10:30 Перерыв
10:50 Упражнения
...
----

Описание:

* Каждая строка начинается со времени, за которым следует описание активности.
* Пустые строки разделяют дни.
* Некоторые активности представляют собой названия лекций, например: `Введение`, `Скаляры`, `Массивы`.
* Некоторые активност представляют собой названия определённых повторяющихся отрезков времени: `Упражнения`, `Перерыв`, `Решения` и т.д.
* Словом `Конец` отмечается конец дня.

== Specification of task 1

* Згенерировать отчёт в виде временных отрезков:

[source, text]
----
09:20-11:00 Введение
11:00-11:15 Упражнения
11:15-11:35 Перерыв
...
----

* Вывести отчет в *Standard Output*

== Specification of task 2

Згенерировать отчёт в виде общего времени, потраченного на активности за день:

[source, text]
----
Лекции: 210 минут 22%
Решения: 95 минут 9%
Перерыв: 65 минут 6%
...
----

* Вывести отчет в *Standard Output*

== Specification of task 3

Згенерировать отчёт в виде детализированного описания лекций и времени, потраченного на них относительно всех лекций:

[source, text]
----
Лекции:
Введение: 23 минуты 5%
...
----

* Вывести отчет в *Standard Output*
